### ISSUE TITLE
the problem when when using transform: scale()

### ISSUE THREAD

**Issue by mfma** [bokuweb/react-rnd#110]
When the parent box add  "transform:scale()", rnd is incorrect to drag or resize it。

**Comment by bokuweb** [comment]
@mfma Could you please provide reproduced project on webpackbin with latest version rnd? https://www.webpackbin.com/bins/-Ku4nRhImIfnt9N08lGu

**Comment by ryanlegler** [comment]
See example below where I've added a "transform:scale()" to parent div.
https://www.webpackbin.com/bins/-KwaJCSIKJcVRtsZ5Hn4

**Comment by bokuweb** [comment]
@ryanlegler Thanks. If you set `transform:scale` to Rnd component directly, `transform` is overwritten by `react-draggable` probably.

See related issue, https://github.com/bokuweb/react-rnd/issues/185

**Comment by ryanlegler** [comment]
@bokuweb thanks for your response - I think the issue described here is slightly different than the related issue you linked to. The scale in question is on a parent div of the react-draggable component. The issue isn't that the scale is overwritten, it's that the pixel calculation made by react-rnd are incorrect because of the scaled context that it's in.  From digging around a bit i found this:  https://github.com/mzabriskie/react-draggable/pull/217/files Looks like this issue is being looked at. Hopefully the pull request will get merged in so the scale param could be exposed in react-rnd.

**Comment by maixing** [comment]
Please merge

**Comment by koutsenko** [comment]
Any news?

**Comment by gaddafirusli** [comment]
Would love to get this one merged too. Any updates?

**Comment by travisdahl** [comment]
I was hoping as an escape hatch that this would work, but alas, it does not...

```
    const style = {
      transform: `translate(${x}px, ${y}px) scale(0.8) !important`
    };

      <Rnd
        style={style}
...
```

**Comment by kv9991** [comment]
+1. Still can't solve this problem
But this looks like good escape https://github.com/mzabriskie/react-draggable/pull/217/files

**Comment by cadrell0** [comment]
The scale prop has been implemented in react-draggable and re-resizable

https://github.com/bokuweb/re-resizable/pull/388
https://github.com/mzabriskie/react-draggable/pull/352

**Comment by mecawish** [comment]
Hi! Can we update the `react-draggable` dependency to the current version? It seems that the `scale` issue is already addressed there.

**Comment by mecawish** [comment]
Working now. Thank you so much, @bokuweb !

**Comment by Hello-Tan** [comment]
> @mfma @ryanlegler @koutsenko @ g33kidd @gaddafirusli @travisdahl @ kv9991 @ cadrell0 @ AhmedSayed77 @mecawish
> 
> 对不起我迟到了。请尝试v9.1.1。
> 
> https://codesandbox.io/s/vmo9ypvwl7

expect support rotate

**Comment by kele5240** [comment]
i can't use rotate when i use Rnd

**Comment by dengnan123** [comment]
> @mfma @ryanlegler @koutsenko @g33kidd @gaddafirusli @travisdahl @kv9991 @cadrell0 @AhmedSayed77 @mecawish
> 
> Sorry for late. Please try v9.1.1.
> 
> https://codesandbox.io/s/vmo9ypvwl7

good!
