### ISSUE TITLE
Drag multiple rnd blocks if bounds is set

### ISSUE THREAD

**Issue by schlesingermatthias** [bokuweb/react-rnd#117]
Hi, 

I'm using react-rnd version 5.0.3 on Chrome 52. 

I want to use multiple react-rnd containers. Everything works fine, except for when I set the `bounds` property. When I do so, the second rnd container can never occupy the space that was initially occupied by the first container (meaning I can drag the first container everywhere, including over the second container, but I cannot drag the second container further left than the rightmost boundary of the initial position of the first container)

Here's my markup:
```
<div style={this.styles.windowContainer} className={"windowContainer"}>
   <Rnd default={{x: 10, y: 10, width: 50, height: 20}} bounds={".windowContainer"}>Test 1</Rnd>
   <Rnd default={{x: 10, y: 10, width: 50, height: 20}} bounds={".windowContainer"}>Test 2</Rnd>
</div>
```

Thanks

**Comment by bokuweb** [comment]
@schlesingermatthias Thanks for your report.I'll do some investigation.

**Comment by Nauss** [comment]
Same problem here using ```bounds="parent"```

**Comment by Nauss** [comment]
The ability to set the bounds with a "rect" ```{ top: 1, left: 2, right: 3, bottom: 4}``` would also be nice.

**Comment by bokuweb** [comment]
@schlesingermatthias @Nauss v5.0.4 published. This issue is solved?

**Comment by Nauss** [comment]
Works exactly like for expected ! Issue is closed for me.
Thanks again for the great work and reactivity :)

**Comment by bokuweb** [comment]
@schlesingermatthias I close this issue. Please re-open this issue, if you need.

**Comment by schlesingermatthias** [comment]
@bokuweb That fixed it. Thanks a lot for your fast response!
