### ISSUE TITLE
Add shortcut property for disabling resizing

### ISSUE THREAD

**Issue by p4bloch** [bokuweb/react-rnd#127]
### Overview of the problem

Currently to disable resizing we need to use `enableResizing` and set every property of `Enable` to `false`, which can be cumbersome and non-intuitive for the user of this library.

### Proposed solution

Wondering if adding a shortcut property, like `disableResizing: boolean` (which will match with `disableDragging`) would make the API easier. Under the hood it will simply be a shortcut for sending an `Enable` object with every property set to false.

What do you think @bokuweb?

**Comment by bokuweb** [comment]
@p4bloch Thanks!! It's a nice idea. But I'm unable to make a decision.Because props feature is deprecated `enableResizing` and `disableResizing`...

**Comment by carly1987** [comment]
But, i set enableResizing to false or true, it will be disableResizing

**Comment by bokuweb** [comment]
Could you please reopen  if you need.
