### ISSUE TITLE
onClick not working

### ISSUE THREAD

**Issue by sajadghawami** [bokuweb/react-rnd#131]
I am not sure if this is a bug or a feature request, but `onClick`doesnt work.

### Description

If `onClick` is set, the event doesnt fire at all.

**Comment by bokuweb** [comment]
@sajadghawami Thanks for your report. Please use `extendsProps`.

```
<Rnd
  extendsProps={{
    onClick: () => {}
  }}
/>
```

**Comment by jchain** [comment]
Does Rnd extendsProps support onMouseDown and onMouseUp? In my code, it supports onClick and onMouseMove but doesn't support onMouseDown or onMouseUp. I'm not sure if the parent element steals the event.

**Comment by sajadghawami** [comment]
I sloved this by adding a `div` inside the `RND` with `width: 100%; height:100%` then i attached all the necessary events i needed to the inner `div`.

hope this helps!

**Comment by soulmatecm** [comment]
i am facing the same problem,i see the release note that extendsProps is removed,how can do this staff now?

**Comment by chandlervdw** [comment]
`onClick` happens after `onDragStop`. How do I fire an event before `onDragStop` if `onMouseDown` prevents event propagation?

**Comment by saqlain1020** [comment]
Use `onGotPointerCapture` with `onClick` onClick will work on desktop and pointer capture will work on mobile devices.

**Comment by sethshivam11** [comment]
@saqlain1020 If i want a double click event in mobile devices, how can I achieve that?

**Comment by saqlain1020** [comment]
> @saqlain1020 If i want a double click event in mobile devices, how can I achieve that?

@sethshivam11 You will have to write custom logic to capture single taps/clicks, and check if there were two clicks within some milliseconds it should be considered a double click, and for single click functionality you will have to add debounce and wait for some milliseconds before executing single click functionality.
