### ISSUE TITLE
How can I change the cursor for undraggable part to be normal?

### ISSUE THREAD

**Issue by xiaoouLi** [bokuweb/react-rnd#137]
Hi there,

I only want the dialog header to be the drag handler. 
        <Rnd
            ref={(dialog) => { this.dialog = dialog; }}
            default={style} bounds={'parent'}
            className={`dialog ${customClass}`}
            onClick={this.onClick}
            dragHandlerClassName=".header"
          >
            <div className="header">
              <ul className="btns">
               .......
              </ul>
              <h2>{title}</h2>
            </div>

            <div className="content">{children}</div>

            <div className="footer">
              <div className="btns">
                .........
              </div>
            </div>
          </Rnd>

While it turns out the cursor is also "move" on the dialog content.
I notice "boxStyle" always sets it as move unless disableDragging is true.

Is there a way to make the cursor only be move when it's on the handler?

Thanks!
Lois

**Comment by nitkapawel** [comment]
You can try the simplest trick:
`<Rnd
    ...
    className="snapshotDialog"
    dragHandlerClassName=".handle"
>`

in CSS:

```
.snapshotDialog {
    cursor: default !important;
}

.snapshotDialog .handle {
    cursor: move !important;
}
```

**Comment by xiaoouLi** [comment]
That's my solution too!

Thanks!

**Comment by dotku** [comment]
But drag still take effect for none draggle place :(
