### ISSUE TITLE
Please please fix the cursor issue..

### ISSUE THREAD

**Issue by xiaoouLi** [bokuweb/react-rnd#153]
I don't want the cursor to always be move..
The style is settable in release 4, but after 5.0.8, it's broken.

Can you please fix it?
Thanks!

**Comment by nitkapawel** [comment]
Also when i set prop `dragHandlerClassName=".handle"` only .handle element should have the cursor: move, the rest of elements should have the default cursor

**Comment by bokuweb** [comment]
@xiaoouLi @nitkapawel Thanks for your report.I'll fix it.
