### ISSUE TITLE
get the current position without callback

### ISSUE THREAD

**Issue by sajadghawami** [bokuweb/react-rnd#160]
Hey there,

i guess this is pretty straight forward:

How do you get the current x and y coordinates for the `RND` without a callbacks?

I didn't find anything in the docs, nor have i found a solution for this.

```
console.log(this.rnd);
```

This doesn't seem to hold the information either. What am i missing?

Thanks.

**Comment by iphonic** [comment]
@sajadghawami You can try this

`console.log("Resized ",this.rnd.resizable.state);`
**Above will give updated width and height and other informations**

`console.log("Dragged ",this.rnd.draggable.state);`
**Above will give updated x and y position and other informations**

Cheers.

**Comment by sajadghawami** [comment]
Thanks, i guess this will do the trick :)
