### ISSUE TITLE
Shaking when resizing the anchor that outside its parent but within its bounds

### ISSUE THREAD

**Issue by Jason121250148** [bokuweb/react-rnd#162]
I am using the 5.0.8 version.
When the rnd is inside bounds but outside its offsetParent,  i resize the left-bottom anchor or left-top anchor(which both reset the x and y), the rnd will shake! That is x : -1 1 -2 2 -3 3....i dont know whether it is bug or i dont use  it correct.

**Comment by bokuweb** [comment]
@Jason121250148 Could you please provide reproduced sample?? If you'd like to use webpackbin. https://www.webpackbin.com/bins/-KtgCwfKgnXqQpQ31OD4

**Comment by Jason121250148** [comment]
I wrote a demo in webpackbin(with the version 7.0.1): https://www.webpackbin.com/bins/-Ku8kSSW1qIG_xwORj_x
In this case, drag the "left-bottom" to resize the box, the box will shake.

**Comment by bokuweb** [comment]
Thanks :)

**Comment by Jason121250148** [comment]
And also in this case，I add "extendsProps={{ onClick: handleClick }}" and find that the prop "extendsProps" does not work in the newest version 7.0.1. That will be very kind of you to check on it.

**Comment by bokuweb** [comment]
@Jason121250148 Could you please use v7.1.3.

thanks!
