### ISSUE TITLE
Wrong position

### ISSUE THREAD

**Issue by iphonic** [bokuweb/react-rnd#166]
**Need Help.**

I am not able to position the component properly in my implementation, see below

![rnd](https://user-images.githubusercontent.com/5745637/30027176-7721a3e2-919d-11e7-9b09-60bb33cc28d6.png)

In the image above the square red area is the area where the Rnd component should actually show, but the component is going beyond this and it is not visible despite the translate x and y position are well inside the red marked area. See the html screenshot below

![rnd2](https://user-images.githubusercontent.com/5745637/30027499-ea533e06-919e-11e7-9b3a-4048334d0b8f.png)

Can you please help to resolve this? Many Thanks.

**Comment by bokuweb** [comment]
@iphonic Thanks for your report. Could you please provide reproduced minimum project? :)

**Comment by bokuweb** [comment]
Could you please try `react-rnd@5.1.1`.

**Comment by iphonic** [comment]
@bokuweb No it didn't fix the problem, but I can make the rnd component visible when I am turning off the transform css, and adding left and top instead see in the image below.. 

![rnd3](https://user-images.githubusercontent.com/5745637/30034208-700df694-91bd-11e7-8287-54db20a73b39.png)

Is there any way to override this ?

**Comment by iphonic** [comment]
I fixed by adding **left:0px** and **top:0px** in inline style of rnd component. Thanks for prompt response and help.. Great component.
