### ISSUE TITLE
why react-resizable minConstraints Non-existent

### ISSUE THREAD

**Issue by namoweixiao** [bokuweb/react-rnd#174]
### Overview of the problem

I'm using react-resizable-box **version** [x.x.x]   
   
My **browser** is:   
   
I am sure this issue is **not a duplicate**?

### Steps to Reproduce

1. First Step
2. Second Step
3. and so on...

### Actual behavior

![image](https://user-images.githubusercontent.com/15919331/30319954-d571dae2-97e3-11e7-857e-96882f498979.png)

**Comment by adjohu** [comment]
[re-resizable](https://github.com/bokuweb/re-resizable) takes `minWidth` and `minHeight` props

**Comment by bokuweb** [comment]
@adjohu Thanks!
