### ISSUE TITLE
maxWidth and maxHeight props don't respect after resize

### ISSUE THREAD

**Issue by NewOldMax** [bokuweb/react-rnd#188]
### Overview of the problem
I'm using react-rnd 7.1.3
https://www.webpackbin.com/bins/-Kut-6Jbwje1eyPBYBQN

My **browser** is:   Chrome  61.0.3163.100 on Windows 10
   
I am sure this issue is **not a duplicate**

### Description
When you resize component, `maxWidth` and `maxHeight` props are replaced with internal calculations

My use case:
I'm building a component which have button "maximize"
![image](https://user-images.githubusercontent.com/1328473/30809033-02b2924c-a209-11e7-812d-474a6be223cf.png)

When user click it, I change `width` and `height` to `100%`. So if user doesn't resize this window, it works fine, but if user resizes it, `maxWidth` and `maxHeight` styles are replaced by internal calculated and after "maximize" window can't fit all screen, because `maxWidth` and `maxHeight` are not `100%`

### Steps to Reproduce

1. Set `maxWidth` and `maxHeight` props to `100%`
2. Resize component
3. Check these styles
4. Drag around and resize again
5. Check these styles

### Expected behavior

After resize end `maxWidth` and `maxHeight` are taken from props

### Actual behavior

After resize end `maxWidth` and `maxHeight` are remain calculated

**Comment by bokuweb** [comment]
@NewOldMax Thanks for your report.
When you use `bounds` property, maxWidth and maxHeight are set computed size calculated by internal logic.If you would like to keep 100% please remove bounds props.

**Comment by NewOldMax** [comment]
But I need to have `bounds`...
It's possible to take `maxWidth` from `props` after resize stop event? Like, ok, you shouldn't resize more that `bounds` element size, but after resize, we don't need to keep this calculated `maxWidth`

**Comment by bokuweb** [comment]
@NewOldMax Thanks. I'm gonna try it.

**Comment by bokuweb** [comment]
@NewOldMax I've published v7.1.4.

**Comment by NewOldMax** [comment]
Thanks! 🍺
