### ISSUE TITLE
Crash in IE11 on window close

### ISSUE THREAD

**Issue by argnist** [bokuweb/react-rnd#199]
It is a bug

### Overview of the problem
I'm using react-rnd 7.1.4
   
My **browser** is:   IE 11
   
### Description

Sometimes when window is closed (running componentWillUnmount) I get error 800a025e in IE. Thats because IE haven't method window.getSelection().removeAllRanges() in removeUserSelectStyles() of react-draggable.
It will not be fired if prop of react-draggable enableUserSelectHack is set to false but react-rnd not passes this property.

### Steps to Reproduce
Close window in IE11.

**Comment by bokuweb** [comment]
@argnist Thanks for your report. I add `enableUserSelectHack`prop to `react-draggable`.

**Comment by argnist** [comment]
Setting to false yields showing selections on text in draggable zone :( That looks not good. I created issue to react-draggable to fix the bug. Could you make enableUserSelectHack settable via Rnd, not hard-coded?

**Comment by bokuweb** [comment]
Please use latest version. Please re-open if you need.
