### ISSUE TITLE
onCopy not working for extendsProps

### ISSUE THREAD

**Issue by volkandkaya** [bokuweb/react-rnd#201]
https://www.webpackbin.com/bins/-KxKg89FdG7eLglzj5E6

### Expected behavior

onCopy to work as onClick does

### Actual behavior

Nothing

I also believe that it is causing problems with other onCopy properties. The code was working fine a few months ago and then I updated my package.json and it isn't working now.

Hopefully, the webpackbin helps, if not let me know.

**Comment by bokuweb** [comment]
@volkandkaya Thanks for your report and reproduced project 👍

**Comment by bokuweb** [comment]
@volkandkaya Would you please try v8.0.1. The below `code` works correctly.

```
import React from "react";
import Rnd from "react-rnd";
import { style } from "../styles";

export default () => (
  <Rnd
    style={style}
    cancel=".cancel"
    default={{
      width: 200,
      height: 200,
      x: 0,
      y: 0,
    }}
  >
    <div
      className="cancel"
      style={{ width: "100px", height: "100px", display: "flex", alignItems: "center", justifyContent: "center" }}
      onCopy={() => console.log('onCopy')}
    >
      001
    </div>
  </Rnd>
);
```
