### ISSUE TITLE
The Demo Code is unaccessible

### ISSUE THREAD

**Issue by Hearen** [bokuweb/react-rnd#203]
https://github.com/bokuweb/react-rnd/blob/master/docs/src/example.js Would you please update this link? Thank you so much.

**Comment by bokuweb** [comment]
Sorry, would you please see webpackbin for now. https://www.webpackbin.com/bins/-Ku4nRhImIfnt9N08lGu

I'm gonna update it :)

**Comment by yandanarendra** [comment]
Can you give the demo code link for this
![screenshot](https://user-images.githubusercontent.com/39962905/41390216-4961f4a4-6fb2-11e8-904c-96b7e4e1afc9.JPG)

**Comment by bokuweb** [comment]
@Hearen @yandanarendra Sorry, I've created codesandbox example.
Would you please see it ?? 

https://codesandbox.io/s/q9onxj77j6
