### ISSUE TITLE
How to change the cursor type of corner

### ISSUE THREAD

**Issue by webstermobile** [bokuweb/react-rnd#204]
Firstly, this is a wonderful react component , Thanks for you !
The following is my question:
I want to change the cursor type of each corner,
default they are : row-resize col-resize ne-resize se-resize sw-resize nw-resize
How can I change theme ?
Looking forward to your reply !
My email : webstermobile@hotmail.com

**Comment by mkg0** [comment]
you can use `resizeHandleStyles` or `resizeHandleClasses` properties for overriding cursor type

```
const topRightStyles = {
  cursor: 'pointer',
}

<Rnd
  {...otherProps}
  resizeHandleClasses={{
    topRight: 'topRightHandleClass',
  }}
  // or
  resizeHandleStyles={{
    topRight: topRightStyles,
  }}
>
</Rnd>
```

**Comment by bokuweb** [comment]
@mkg0 Thanks :)

**Comment by webstermobile** [comment]
Thank u pretty much !

**Comment by gavinpark** [comment]
Is it possible to use this method but use a custom .png as the cursor?
