### ISSUE TITLE
zIndex seems to be not applying in v7

### ISSUE THREAD

**Issue by gsharath** [bokuweb/react-rnd#208]
Hi,

Thanks a lot for this great component. Its helping me a lot to drag and drop the required elements.

I have an issue while setting zindex of an element. 
I am trying to set zIndex dynamically in version 7.1.5 and when i check zindex by inspecting element, i am not able to see zindex applied. 

After checking out for this issue, found out I checked https://github.com/bokuweb/react-rnd/issues/52 link and so I tried to go back and use version and do the same above steps with changing my code, i am able to see z-index. 

Not sure if I am missing something else to set with the latest version.
Can you guide me on how to set zindex for the Rnd component in version 7.1.5

**Comment by bokuweb** [comment]
@gsharath I removed `z` props in v8. Would you please pass `zIndex` via `style`

```
<Rnd style={{ zIndex: 999 }}>Foo</Rnd>
```

**Comment by horumyy** [comment]
what if the zIndex is dynamically, i see no changes on UI but the element does get the zIndex value updated on the brower
