### ISSUE TITLE
Bounds checking bugs

### ISSUE THREAD

**Issue by tauren** [bokuweb/react-rnd#209]
### Overview of the problem

I'm finding several bugs related to bounds checking.

1. When `bounds="window"`, attempts to drag the Rnd cause it to move to top left of window. You can resize it without it moving, but when you then try to drag, it moves. See it here:
https://www.webpackbin.com/bins/-L-ZFjL6mq72pTvbHIHU

2. When `lockAspectRatio` is set and `bounds="parent"`, it is possible to resize the Rnd outside of the lower bounds. First move the Rnd to the bottom of the window, then resize it from the left or right edge. The bottom will grow past the bottom edge of the window. Additional resizes from other edges/corners keep the Rnd in the same position. But clicking it to drag causes it move so the entire Rnd is within the bounds. See it here:
https://www.webpackbin.com/bins/-L-ZHTV_IdyFrlUr-jip

3. My understanding is the `bound` can take a selector. However `bounds="body"` doesn't seem to work as expected.

**Comment by romanlex** [comment]
Hello, your solve this issues?

**Comment by bokuweb** [comment]
Thanks for your reports. I'll investigate it.

**Comment by tnrich** [comment]
Any update on this @bokuweb ? It would be great if we could provide programatic bounds. Also having an option to bound using the viewport (as opposed to the <body> element) would be great! Sometimes <body> does not scale to fit content or is larger than the viewport. 

Thanks!

**Comment by bokuweb** [comment]
Sorry...  I have not started yet.

**Comment by tnrich** [comment]
No problem. I do think a "viewport" or "window" option would be helpful.

**Comment by bokuweb** [comment]
@tnrich Thanks for your proposal :) I will consider it soon.

**Comment by bokuweb** [comment]
fix bounds `parent` behaivior in this PR https://github.com/bokuweb/react-rnd/pull/378/files#diff-38682f47b0cf12c516bc3714fc45d0fdR233

**Comment by bokuweb** [comment]
you can check `window` bounds here http://bokuweb.github.io/react-rnd/stories/?selectedKind=bounds&selectedStory=window%20controlled&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by bokuweb** [comment]
@tauren @romanlex @davitv @tnrich I published v8.0.0.
Would you please try `window` bounds.

https://codesandbox.io/s/pmo783mp0j

**Comment by bokuweb** [comment]
I 'll do an implementation of `programmatic bounds` and do an investigation of `lockAspectRatio` bug.

**Comment by bokuweb** [comment]
@tauren @romanlex @davitv @tnrich  Hi, this issue solved by v8.0.2. would you please try the latest version?

- [x] fix `window` bounds
- [x] add `body` bounds
- [x] fix boundary when `lockAspectRatio` set.

I'll do programable bounds impletion in the future. https://github.com/bokuweb/react-rnd/issues/388

I close this issue, for now. If you find new problem, please reopen this issue or create new one.

**Comment by tnrich** [comment]
Seems to work for me @bokuweb 

Thanks!!
