### ISSUE TITLE
When using position not able to resize in all direction

### ISSUE THREAD

**Issue by Thilagm** [bokuweb/react-rnd#215]
### Overview of the problem

I'm using react-rnd **version** [x.x.x]   16.1.1
   

https://www.webpackbin.com/bins/-L2L9lheLunEuwnlFL0A

My **browser** is:   chrome
   
I am sure this issue is **not a duplicate**? Not duplicate

### Steps to Reproduce

1. use size and position in Rnd
2. try to resize from top and left, not able to resize in that direction

**Comment by bokuweb** [comment]
@Thilagm Sorry.. Could you please reproduced project with codesandbox https://codesandbox.io/s/my4kjly94x, if you get a chance. Because webpack bin is dead.

**Comment by ryanmarshall** [comment]
@Thilagm I had the same issue and it was fixed when i changed my resize callback from "onResizeStop" to "onResize."

**Comment by bokuweb** [comment]
Please try this sample.


```
<Rnd
  size={{ width: this.state.width,  height: this.state.height }}
  position={{ x: this.state.x, y: this.state.y }}
  onDragStop={(e, d) => { this.setState({ x: d.x, y: d.y }) }}
  onResize={(e, direction, ref, delta, position) => {
    this.setState({
      width: ref.style.width,
      height: ref.style.height,
      ...position,
    });
  }}
>
  001
</Rnd>
```
