### ISSUE TITLE
how prevent dragging on child element

### ISSUE THREAD

**Issue by iamnotstone** [bokuweb/react-rnd#217]
I am using <input> element as a child element of <rnd>. Is there any way to prevent dragging action when a want to select content in the input box?

**Comment by dr15** [comment]
Hey, you can use this: https://github.com/bokuweb/react-rnd#cancel-string
Just pass a string with a class name to the 'cancel' prop, and give this class name to the child element

**Comment by iamnotstone** [comment]
Thanks for your reply. I'll try your suggestion to improve my project. 
I solved this problem on this way, but it's not elegant enough:

  `onChildrenMouseOver(e){                                                                   
    e.preventDefault()
    this.disableDragging()                                                                  
  }                                                                                         
  
  onChildrenMouseOut(e){                                                                    
    e.preventDefault()
    this.enableDragging()                                                                   
  }   `

**Comment by bokuweb** [comment]
@dr15 Thanks :)

@iamnotstone Please use `cancel` props.

http://bokuweb.github.io/react-rnd/stories/?selectedKind=cancel&selectedStory=cancel&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
