### ISSUE TITLE
How to force resize only square

### ISSUE THREAD

**Issue by khoaanh2212** [bokuweb/react-rnd#223]
I have a case,just allow user can resize in square type.How can i do that?
Thanks

**Comment by bokuweb** [comment]
@khoaanh2212 Could you please use `bounds` props.

**Comment by khoaanh2212** [comment]
@bokuweb does Bounds props use for drag and drop? my problem is about resize item,when i resize,mouse can make item resize like rectangle.and i want to force resize item just in square.
How can i do that?
