### ISSUE TITLE
The webpackbin example that appears in the readme file is not working

### ISSUE THREAD

**Issue by TamarAmit** [bokuweb/react-rnd#225]
bug, not related to a browser  (tested on both firefox, chrome and explorer)
### Overview of the problem

I am trying to open the webpackbin project from the latest [link](https://www.webpackbin.com/bins/-KyeXupuBJyBPaIN0F_i) 

But nothing is presented on the right area of the page, and then I receive the following message:
"Sorry, something went wrong, please report or refresh"

It can be reproduced here:
https://www.webpackbin.com/bins/-KyeXupuBJyBPaIN0F_i

My **browser** is:   chrome, firefox or explorer (it didn't work on none of them)
   
I verified that it is not duplicated :)

### Description

The main example in webpackbin doesn't load properly
 
### Steps to Reproduce

1. First Step:
Open https://www.webpackbin.com/bins/-KyeXupuBJyBPaIN0F_i

### Expected behavior

the example is presented

### Actual behavior

Got an error : "Sorry, something went wrong, please report or refresh"

**Comment by TamarAmit** [comment]
This is the console output:
-----------------------------
main.js Failed to load resource: the server responded with a status of 404 (Not Found)
sandbox.webpackbin.com/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
sandbox.webpackbin.com/:1 Access to Script at 'https://webpack-dll-prod.herokuapp.com/v6/react-dom%4015.4.2%2Breact-rnd%407.1.5%2Breact%4015.4.2/dll.js' from origin 'https://sandbox.webpackbin.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://sandbox.webpackbin.com' is therefore not allowed access. The response had HTTP status code 503.
main.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by bokuweb** [comment]
Thanks :) Please use codesandbox https://codesandbox.io/s/y3997qply9
