### ISSUE TITLE
dragStop img tag need click mouse？

### ISSUE THREAD

**Issue by 823844596** [bokuweb/react-rnd#229]
is it a bug of react rnd?

###
i use react-rnd with the 7.3.0 version

##
my browser is chrome 64.0.3282.167.

### Description
i use img tag in Rnd, when i drop img, i need to click mouse to drop the img, my code is:

     <Rnd ref={id => { this.rnd = id; }} 
         default={{ x, y, width, height }}
         minWidth={minWidth} minHeight={minHeight}
         maxWidth={maxWidth} maxHeight={maxHeight}
         size={{ width: width,  height: height }}
         bounds='parent'
         enableResizing={{top:false, right:true, bottom:true, left:false,
           topRight:false, bottomRight:true, bottomLeft:false, topLeft:false}}
        onDragStop={handleDragStop} 
        onResizeStop={handleResizeStop}>
          <img src={'1.png'} width={'100%'} alt='' height={'100%'}  />
    </Rnd>

and i found react-rnd need react-draggable dependencies, and the react-draggable open an issue : https://github.com/mzabriskie/react-draggable/issues/304,  this problem is due to it?

### Expected behavior
if i release the mouse， the img tag need to be in the mouse position.

### Actual behavior
when i release the mouse, i need to click mouse to confirm the position of img tag.

would you give me help? thanks~
@bokuweb

**Comment by Adamkzh** [comment]
got the same problem.

**Comment by Adamkzh** [comment]
Solve the problem by adding ` onMouseDown={ (e)=> {e.preventDefault()}}`  
The first click just like onMouseDown action.

**Comment by 823844596** [comment]
got it, thanks~

**Comment by Adamkzh** [comment]
@bokuweb 
This but still not solve yet. Hope you can help with this.

**Comment by bokuweb** [comment]
@Adamkzh Sorry, could you please provide reproduce project ( by code sandbox https://codesandbox.io/s/y3997qply9), if you get a chance?

**Comment by Adamkzh** [comment]
[https://codesandbox.io/s/vjn2jw0zk5](https://codesandbox.io/s/vjn2jw0zk5)

Check this out. It works fine on Mobile. but for chrome & firefox it not work.

**Comment by bokuweb** [comment]
@Adamkzh Thanks :)

@823844596 @Adamkzh I think, we need to add `draggable={false}` to `<img />`.

https://codesandbox.io/s/2zzkrv55ry

**Comment by bokuweb** [comment]
It is wondering whether this component adds `draggable = {false}`, but we think that it is better to add it on the user side...

**Comment by Adamkzh** [comment]
@bokuweb Thank you so much.

**Comment by VarunRustomji** [comment]
https://github.com/bokuweb/react-rnd/issues/229#issuecomment-375931548

In this solution, when I add `bounds="window"` prop it doesn't seem to work correctly.. Any idea why this could be the case?
