### ISSUE TITLE
marker position changes as screen size is altered

### ISSUE THREAD

**Issue by silentarrowz** [bokuweb/react-rnd#298]
**I need help with a problem that needs fixing or maybe this is a bug. dont know for sure**

### Overview of the problem
**I am displaying an image and then using a marker on it. the problem is that when the screen size is altered. the marker also changes its position, why is this happening? and how can I fix this so that the marker stays on the same position relative to the image.** here's the link -> [https://codesandbox.io/s/34x4lrovmm](https://codesandbox.io/s/34x4lrovmm)

I'm using react-rnd **version** [5.1.1]   
      
**My **browser** is:   Chrome**
   
I am sure this issue is **not a duplicate**? _Yes, I am quite sure of that._
   
### Steps to Reproduce

**1. display an image in a div
2. display the marker on div
3. alter browser window size**

### Expected behavior
marker should have stayed on same position relative to image

### Actual behavior

marker's position keeps changing as screen size changes and thus it shows up at a different
place on the map image.

**Comment by silentarrowz** [comment]
issue solved

**Comment by motro** [comment]
@silentarrowz, would you mind sharing your solution please?
Thanks!

**Comment by silentarrowz** [comment]
my solution was that I put the map image I was using to position absolute and the position of booth to relative. so, booth was moving relative to image and therefore it was always on same position on map no matter how much I moved it or scaled it.
