### ISSUE TITLE
resize and drag performance issues in IE11 (throttle)

### ISSUE THREAD

**Issue by haakemon** [bokuweb/react-rnd#307]
### Overview of the problem

See [issue #248 on re-resizable](https://github.com/bokuweb/re-resizable/issues/248) for the same issue on resizing

I might be able to work on this myself, but not right now. I also would like to see if a PR would be accepted for this first.

I'm using **version** 7.4.0
   

My **browser** is:   Internet Explorer 11
   
I am sure this issue is **not a duplicate**

### Description

When resizing or dragging containers in IE11, the experience is not smooth. The more complex the container, the more "lag" will be experienced. My use case involves a fairly complex container and it is barely usable in IE11.

### Steps to Reproduce

1. Create a slightly more complex container than a simple div to resize or drag
2. Resize or drag the div
3. The dragging and resize wil be "lagging" because of the repeated calculations runnning, and IE's crappy JS engine.

### Expected behavior

A smoother resize and dragging experience in IE

### Actual behavior

Lagging when resizing and dragging

**Comment by eps1lon** [comment]
Could also be a problem of your container that does unnecessary render calls. Have you checked react devtools and confirmed that some nested component in your container is not firing every time you resize?
