### ISSUE TITLE
Programmatically trigger a drag start?

### ISSUE THREAD

**Issue by vincentbollaert** [bokuweb/react-rnd#316]
I'm using react-rnd **7.4.0**

Does react-rnd support programmatically triggering drag events? It was requested for react-draggable, which this lib uses: https://github.com/mzabriskie/react-draggable/issues/89 but was seen as out-of-scope

**Comment by bokuweb** [comment]
@vincentbollaert Sorry. Currently impossible and there is no plan for implementation.
