### ISSUE TITLE
dragHandleClassName anomalies

### ISSUE THREAD

**Issue by idleberg** [bokuweb/react-rnd#335]
### Overview of the problem

I'm using react-rnd v7.4.0
      
My **browser** is:   Chrome v66.0.3359.181 (Official Build) (64-bit)
   
### Description

*I'm not reporting a bug, but some anomalies that I find confusing and *could* (or should) be changed.*

I find the `dragHandleClassName` property a bit confusing. As its name suggests, it expects a class name, so the need to provide a leading dot (e.g. `.className`) makes little sense. Personally, I think the current behaviour would make sense for a more general `dragHandleSelector` property, whereas `dragHandleClassName` should follow the `getElementsByClassName` convention and omit a leading dot. Since this would be a breaking change, I'd suggest allowing both.

I have also noticed, that with that same property defined, the cursor isn't set  `move` like when it's undefined. Was this intentional or is it an oversight?

**Comment by bokuweb** [comment]
@idleberg I see.

> this would be a breaking change

Hmm, I started to v8,  so I will change it to `no dot` string at this timing.

#379

**Comment by bokuweb** [comment]
fixed by v8.0.0.
