### ISSUE TITLE
Prevent component's child from resize and drag actions

### ISSUE THREAD

**Issue by Grsz** [bokuweb/react-rnd#386]
It's possible right now to handle the Rnd component's child, but just the child as an "independent" element? I have a component which is just a box with an X button which closes the box, but if i click on it, the Rnd component handles the click as a drag, which leads to bugs.

**Comment by bokuweb** [comment]
@Grsz Please try `cancel` props.

http://bokuweb.github.io/react-rnd/stories/?selectedKind=cancel&selectedStory=cancel&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

https://github.com/bokuweb/react-rnd#cancel-string

**Comment by pingbaohua** [comment]
网址打不开了，第一个，已到其他位置了吗
