### ISSUE TITLE
Drag image is lagging

### ISSUE THREAD

**Issue by piavgh** [bokuweb/react-rnd#402]
### Overview of the problem

I'm using react-rnd **version** [8.0.2]   
      
My **browser** is: Google Chrome latest version
   
I am sure this issue is **not a duplicate**?
   
### Reproduced project

https://codesandbox.io/s/zr0nyx7qmx

### Steps to Reproduce

1. Drag the text, it's very smooth
2. Drag the image below, it's kind of lagging and even when I release the left-mouse, the image is still attached to the mouse and I can still drag it.

### Expected behavior

Dragging image should be as smooth as dragging the text.

### Actual behavior

You can see more in this video: https://screencast-o-matic.com/watch/cFi0olFdn8

**Comment by bokuweb** [comment]
@piavgh Thanks for your report.

Please add `draggable={false}` to `img` element.

https://codesandbox.io/s/mj4o972kjj

**Comment by piavgh** [comment]
Thank you very much
