### ISSUE TITLE
Unable to change value in "Input" field inside Rnd

### ISSUE THREAD

**Issue by devbazilio** [bokuweb/react-rnd#403]
### Overview of the problem

I'm using
```
"dependencies": {
    "react": "16.4.1",
    "react-dom": "16.4.1",
    "react-rnd": "8.0.2",
    "react-scripts": "1.1.0"
  }
```      
My **browser** is:  Chrome 67.0.3396.99
   
   
### Reproduced project

https://codesandbox.io/s/50xlmvqpwl

### Steps to Reproduce

1. Open link above in Chrome
2. Try to change a text in input
3. And nothing was changed
4. FF - it's working

### Expected behavior
Content of input should be updated

### Actual behavior
Text of input can not be updated 

UPD:
I removed "mousedown" event listener in Developer tools, and it works :), but Rnd becomes unmovable

**Comment by devbazilio** [comment]
I fixed that by adding listener
```
<input onMouseDown={e => e.stopPropagation()}/>
```

**Comment by bokuweb** [comment]
@devbazilio Thanks :)

We can use `cancel` props too.

https://github.com/bokuweb/react-rnd#cancel-string

**Comment by liu550** [comment]
How exactly should we use the "cancel" property to fix the issue, given that we have the id of the input element?

**Comment by JordanWinslow** [comment]
> How exactly should we use the "cancel" property to fix the issue, given that we have the id of the input element?
```
<Rnd 
...
cancel="#yourId"
>
<input id="yourId" />
...
</Rnd>
```
