### ISSUE TITLE
no default export in es5 distribution

### ISSUE THREAD

**Issue by farfromrefug** [bokuweb/react-rnd#405]
if you look at the distributed es5 version there is no default export but a ```module.exports = Rnd;```

Consequently you can't do 
```
import Rnd from 'react-rnd';
```
But you must do 
```
import * as Rnd from 'react-rnd';
```

As a consequence typings won't work with the es5 release

**Comment by bokuweb** [comment]
@farfromrefug Thanks for your report :) I fixed this issue. could you please try latest version if you would not mind. 

typescript example is here.
https://codesandbox.io/s/j1vvkpo9wv

**Comment by farfromrefug** [comment]
@bokuweb works fine now just not a "default" export. Might just need to change to doc.

Thanks for that fast fix!
