### ISSUE TITLE
CSS transform property is ignored in style

### ISSUE THREAD

**Issue by devbazilio** [bokuweb/react-rnd#410]
### Overview of the problem

I'm using
```
"dependencies": {
    "react": "16.4.1",
    "react-dom": "16.4.1",
    "react-rnd": "8.0.2",
    "react-scripts": "1.1.0"
  }
```      
My **browser** is:  Chrome 67.0.3396.99
      
  
### Reproduced project
https://codesandbox.io/s/3qyjyy1v3p

### Steps to Reproduce

Add _transform_ and _opacity_ properties

### Actual behavior

Transform property is ignored
Opacity works.

**Comment by Aquarius-Sally** [comment]
how does it work?
