### ISSUE TITLE
"export 'default' (imported as 'Rnd') was not found in 'react-rnd'

### ISSUE THREAD

**Issue by matiasbenedetto** [bokuweb/react-rnd#419]
The console is getting me this:
`"export 'default' (imported as 'Rnd') was not found in 'react-rnd'`

And when a i want to render the app with a <Rnd/> i get this error:

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`

**Comment by justswim** [comment]
You should import it like this:
`import { Rnd } from 'react-rnd';`

**Comment by bokuweb** [comment]
@justswim Thanks!!
