### ISSUE TITLE
resizeHandleWrapperClass warning shown in console

### ISSUE THREAD

**Issue by justswim** [bokuweb/react-rnd#428]
Bug when using the resizeHandleWrapperClass prop. Warning shows in console: `Warning: React does not recognize the `resizeHandleWrapperClass` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `resizehandlewrapperclass` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

### Overview of the problem

I'm using react-rnd ^9.0.1
      
My **browser** is:  Chrome Version 68.0.3440.106 (Official Build) (64-bit)
   
I am sure this issue is **not a duplicate**?
 Yes

### Reproduced project

https://codesandbox.io/s/0xr1mzovmv

The class is applied to the span tag, but the warning remains in the console.

**Comment by justswim** [comment]
Note, the codesandbox console doesn't seem to show the warning. I'm not sure why. But if you inspect element with the Chrome inspector, the warning will be there.

![screen shot 2018-08-24 at 2 38 37 pm](https://user-images.githubusercontent.com/1372528/44609146-6fb24380-a7ab-11e8-9645-2630a05786e4.png)

**Comment by bokuweb** [comment]
@justswim Thanks for your report :) I've published v9.0.2 🎉
