### ISSUE TITLE
Unable to Edit <input /> when added inside Rnd

### ISSUE THREAD

**Issue by sampathkatari** [bokuweb/react-rnd#436]
### Overview of the problem
Unable to edit an input when added into Rnd component.
Using react-rnd version - ^9.0.2
   
### Reproduced project
https://codesandbox.io/s/y3997qply9

### Steps to Reproduce
1. Open the codesandbox you provided 
2. Add an input inside <Rnd></Rnd> and try to edit. 
3. We won't be able to edit it. 
4. But if we try to click and without releasing the mouse pointer and edit, it works !!

### Expected behavior

We should be able to edit input element that is added, as we might have forms added in a draggable container.

Please help!!

Thanks.

**Comment by bokuweb** [comment]
@sampathkatari Please see https://github.com/bokuweb/react-rnd/issues/403.

I'll add some example to storybook.
