### ISSUE TITLE
Losing focus when input or textarea is inside of rnd

### ISSUE THREAD

**Issue by SebastianKaczanowski** [bokuweb/react-rnd#461]
### Overview of the problem
It is impossible to use input or textarea inside of Rnd tag because they are losing focus all the time.
I think it is a bug because it was working in version 5.0.3.

I'm using react-rnd **version** [9.0.2]   
      
My **browser** is:  chrome and edge 
   
I am sure this issue is **not a duplicate**?
I'm not sure, some issues are in language which I do not understand.
   
### Reproduced project

Kind of easy to do, create new project using react-scripts add rnd to it and change content of App.js to:

````
import React, { Component } from 'react';
import { Rnd } from 'react-rnd';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <Rnd>
                <input/>
          </Rnd>
        </header>
      </div>
    );
  }
}

export default App
````

### Steps to Reproduce

1. Click on input field and you will loose focus immediately. 

### Expected behavior
Focus should stay on input, or textarea field.

### Actual behavior
Focus is switched to body as far as I understand. I think it is because of changing some css class in body tag, but I'm not sure.

**Comment by chathuraa** [comment]
I am experiencing the same issue :(

**Comment by chathuraa** [comment]
hi @SebastianKaczanowski ,

I've fixed the issue with making enableUserSelectHack prop to false

thanks,
Chat

**Comment by bokuweb** [comment]
@SebastianKaczanowski @chathuraa Please see https://github.com/bokuweb/react-rnd/issues/436

**Comment by AlcuinGuest** [comment]
@chathuraa 's answer allows you to drag the input as well as edit the text, while the other solutions seem to block one or the other 👌🏽
