### ISSUE TITLE
Settings: dragAxis and bounds arec ompletly ignored

### ISSUE THREAD

**Issue by matiasbenedetto** [bokuweb/react-rnd#463]
### Overview of the problem

I'm using react-rnd **version** [9.0.1]   
      
My **browser** is:   Chromium version 70.0.3538.77 (Build oficial) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)
   
### Reproduced project

https://codesandbox.io/s/9y91qkwpqr

### Description

Settings "dragAxis" and "bounds" are completly ignored by react-rnd. I adedd this two setting in the default test project on codesandbox and i can drag the Rnd componente freely in both axis, and the bounds dosn't seem to work in the test project neither in my local dev enviroment.

### Expected behavior

The expected behavior is to drag only in the direction setted and the bounds are respected.

### Actual behavior

Settings "dragAxis" and "bounds" are completly ignored by react-rnd

**Comment by cyberwisdom** [comment]
`dragAxis` and `bounds` are not part of the `default` prop.  

Try this: 
``` 
    style={style}
    default={{
      x: 0,
      y: 0,
      width: 320,
      height: 200,
    }}
    dragAxis='y'
    bounds='window'

**Comment by matiasbenedetto** [comment]
Yes @cyberwisdom. Now is working ok.
Thanks!
