### ISSUE TITLE
Update to react-draggable 3.1.1

### ISSUE THREAD

**Issue by elie222** [bokuweb/react-rnd#479]
### Overview of the problem

I'm using react-rnd **version** [9.0.4]   
      
My **browser** is:   Chrome 71
   
I am sure this issue is **not a duplicate**
   
### Reproduced project

https://codesandbox.io/s/y3997qply9

### Description

Doesn't work with latest react-draggable 3.1.1 when using Typescript.

### Steps to Reproduce

Install react-rnd and react-draggable 3.1.1 in the same project.

### Actual behavior

Typescript project should compile.

**Comment by elie222** [comment]
Will post a PR with a fix shortly.

**Comment by bokuweb** [comment]
@elie222 Please try 9.1.1 :)
