### ISSUE TITLE
When using redux, can't short-circuit setState, which creates memory leak

### ISSUE THREAD

**Issue by jamespfarrell** [bokuweb/react-rnd#498]
I believe I have found a bug.

### Overview of the problem
I have a use case where I'm using redux and when I'm calling action from onDragStop. After onDragStop is called Draggable (used by RND) continues and wants to set state. However the component is unmounted due to redux re-render, and I get this error:

> index.js:1446 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Draggable (created by Rnd)
    in Rnd (at Notes.js:122)
    in div (created by Context.Consumer)

It creates a memory leak because it is trying to setState while the component isn't mounted.
 
**I have fixed this on my fork:**

Rnd onDragStop is called from Draggable, which has a short circuit if you don't want to continue and setState onDragStop. We just need to return false. I returned false from my onDragStop but it seems that Rnd doesn't return false from it's onDragStop. 

I have forked the library and made the necessary change and will make a pull request for you to see.

I'm using react-rnd **version** [9.1.1]   
      
My **browser** is:   

Google chrome

I am sure this issue is **not a duplicate**!!!! :)
   
### Reproduced project
Check the pull request on my fork, it's a 1 line change

**Comment by bokuweb** [comment]
@jamespfarrell 9.1.2 published

**Comment by jamespfarrell** [comment]
You're welcome, thanks for all your hard work, and super cool library!
