### ISSUE TITLE
Ability to close component

### ISSUE THREAD

**Issue by queeniema** [bokuweb/react-rnd#515]
### Overview of the problem

I'm using react-rnd **version** 9.1.1
      
My **browser** is: Google Chrome Version 73.0.3683.103
   
I am sure this issue is **not a duplicate**? Yes

### Description

Would it be possible to add the ability to close the component with a close button?

**Comment by LukeClone** [comment]
You can handle this easily with react 

```
const [toggleRnd, rndOpen] = useState(false)

render => () => (
  rndOpen ? (
    <Rnd ... >
      <div className='header'>
        <button onClick={toggleRnd(!rndOpen)}>x</button>
      </div>
      ...
    </Rnd
) : null
)
```

**Comment by bokuweb** [comment]
@LukeClone Thanks :)
