### ISSUE TITLE
zIndex seems to be not applying

### ISSUE THREAD

**Issue by amitava82** [bokuweb/react-rnd#52]
It seems to get applied on first render but it is not getting applied if pass through props (setting zIndex dynamically). It worked fine in v3.

**Comment by amitava82** [comment]
OK, after some debugging, It seems you removed the div with style that has zIndex and that is what being checked in react-draggable 
https://github.com/bokuweb/react-draggable-custom/blob/master/lib/Draggable.es6#L29

https://github.com/bokuweb/react-rnd/blob/c73699ea10adeacc8809ff7d075827ad7dd6c8b0/src/index.js#L200

Perhaps you should remove this check (this.state.dragging) and always allow pass zIndex through props?
https://github.com/bokuweb/react-draggable-custom/blob/master/lib/Draggable.es6#L278

**Comment by bokuweb** [comment]
@amitava82 thanks for your report. I try to fix it. please try v4.0.1.

**Comment by amitava82** [comment]
Thanks for quick fix! Works perfect!
