### ISSUE TITLE
When using onResizeStop left\top changes opposite coordinate

### ISSUE THREAD

**Issue by regulyarniy** [bokuweb/react-rnd#526]
It's a bug

### Overview of the problem
When using onResizeStop left\top changes opposite coordinate
Demo: https://codesandbox.io/s/nostalgic-tereshkova-lf0cw

I'm using react-rnd 9.1.2
      
My **browser** is:   Chrome
   
I am sure this issue is **not a duplicate**?
It's same as https://github.com/bokuweb/react-rnd/issues/215 but it's closed because inactivity/not working demo
Using onResize instead of onResizeStop is not useful because performance issues
   
### Reproduced project
https://codesandbox.io/s/nostalgic-tereshkova-lf0cw

### Description

Container resized in wrong direction with using onResizeStop callback

### Steps to Reproduce

1. Pull left\top left\top side of container

### Expected behavior

Container changes size in pull direction

### Actual behavior

Container changes opposite size (if you pulled to left it will grow to right etc..)

**Comment by bokuweb** [comment]
@regulyarniy Please use `onResize` like following

https://codesandbox.io/s/distracted-haze-5kcyq

If you use `position` and `size` props, you need to manage position yourself when resizing.

**Comment by bokuweb** [comment]
I'll try improve it when I have time

**Comment by regulyarniy** [comment]
> I'll try improve it when I have time

@bokuweb Thank you! Maybe I could help with it and prepare a PR? Should I look at **bokuweb/re-resizable**?

**Comment by bokuweb** [comment]
@regulyarniy 

> Should I look at bokuweb/re-resizable?

No, we should update `react-rnd`.

>  I could help with it and prepare a PR?

I'm happy. However I think it is a bit complex... 😭  
I'll fix it later when I have time. But I'm busy now....

**Comment by Leslie2014** [comment]
Is now the problem solved?

**Comment by bokuweb** [comment]
@regulyarniy @Leslie2014  This issue was fixed by v10.0.0

**Comment by gustavopch** [comment]
@bokuweb There's still a bug when you use `bounds="parent"` with `onResizeStop`.

## Reproduction steps
- Open my sandbox: https://codesandbox.io/s/nice-http-u5iho?fontsize=14
- Drag the top-left handle up or down
- See how the box jumps
