### ISSUE TITLE
Rnd can be smaller than children divs 

### ISSUE THREAD

**Issue by KMouratidis** [bokuweb/react-rnd#550]
### Overview of the problem

I'm using react-rnd **version** [8.0.1] (npm version from July 3rd)   
      
My **browser** is:   
   Chromium
Version 75.0.3770.90 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

I am sure this issue is **not a duplicate**?
I did take a look at open issues, and used the search functionality, so mostly sure.
   
### Reproduced project

https://codesandbox.io/s/keen-jepsen-bi1y1

### Description

The minWidth of `Rnd` can become smaller than the children divs.

### Steps to Reproduce

1. Add a children div with one or more elements (maybe `inline-block`).
2. Resize `Rnd` to smaller width than the children div.

### Expected behavior

That the `Rnd` would not resize to smaller width than the children.

### Actual behavior

It does!

I know that I can set `minWidth` myself, but I cannot know in advance the children, or their `minWidth`s.

Edit for pic:
![image](https://user-images.githubusercontent.com/26832680/60654197-2d8a7180-9e54-11e9-9781-143154af220f.png)

**Comment by derblitz** [comment]
Is there a possibility to solve this?

**Comment by eddyw** [comment]
Hey, it's fairly easy to do. There are severals ways of doing it, first get the ref of the element, then you can use `getComputedStyles` or just `clientWidth/clientHeight` (but this doesn't take into account margins). I did this quick (updated dependencies):

https://codesandbox.io/s/flamboyant-meitner-mfynq

You can drap/resize both and minWidth/minHeight gets updated according to elements' computed styles (we get width/height and margins if set), besides that, you need to take into account the margins | borders of the wrapping component.

**Comment by KMouratidis** [comment]
Much better than my attempt to resize the smallest of the two (parent/children) to match the bigger. Thanks for the solution! I'm closing this.
