### ISSUE TITLE
Bounds=parent doesnt work when resizing. 

### ISSUE THREAD

**Issue by ErrorPro** [bokuweb/react-rnd#57]
Hi. Is there any way to set up bounds for resizing? For dragging it works perfect.

**Comment by bokuweb** [comment]
@ErrorPro thanks for your report .it is a bug.it will need implement `bounds` function to `react-resizable-box`.

**Comment by bokuweb** [comment]
Fix this bug on @v5.0.0-rc.1

**Comment by bokuweb** [comment]
Please see example.

See demo: http://bokuweb.github.io/react-rnd/
demo Code: https://github.com/bokuweb/react-rnd/blob/master/docs/src/example.js
