### ISSUE TITLE
Strange behavior of lockAspectRatioExtraHeight prop

### ISSUE THREAD

**Issue by vlukyanoff** [bokuweb/react-rnd#579]
### Overview of the problem

I'm using react-rnd **version** [10.0.0]   
      
My **browser** is:  Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)
   
I am sure this issue is **not a duplicate**
   
### Reproduced project

https://codesandbox.io/s/sparkling-dawn-wfxfg

### Description

When I add lockAspectRatioExtraHeight prop and try to resize, size and ratio of block changed. Look at the gif:

![gif](https://user-images.githubusercontent.com/17062961/63331231-4ab4ca00-c346-11e9-8014-eff42a61c07c.gif)

### Steps to Reproduce

1. Try to resize of element

**Comment by vlukyanoff** [comment]
I found my mistake.
lockAspectRatio prop should be a number, for example:
https://codesandbox.io/s/little-https-w2zq7

**Comment by lmcarreiro** [comment]
Thank you so much for sharing this solution.

I had the same issue here and lost some good hours of working until I make this right. I think it deserves a better description on the README.md file on how to use `lockAspectRatio` with `lockAspectRatioExtra[Width|Height]`.

I was trying `lockAspectRatio=true` and `lockAspectRatioExtra=numericValue` first. I also lost some time trying the wrong numeric value on `lockAspectRatio`, I was including the fixed height in the `width/height` calculation.
