### ISSUE TITLE
touch problems to resize elements

### ISSUE THREAD

**Issue by andrejunges** [bokuweb/react-rnd#58]
Hey, I think we have an issue with touch support when resizing elements.
I haven't gone through all the code, but I could trace the problem..

I'm not sure why the whole `event` isn't passed forward in this line
https://github.com/bokuweb/react-resizable-box/blob/master/src/resizer.js#L91

But if we do that, we can't call `e. stopPropagation` here. Not sure if it needs to be stopped (probably it does), but if it doesnt, we could just test if the object has that function.
https://github.com/bokuweb/react-rnd/blob/master/src/index.js#L134

Otherwise we could pass the whole event and adapt the other function to work properly with this change.

Am I missing something?
What do you think about it?

**Comment by bokuweb** [comment]
@andrejunges thanks your your report. I'll fil it. Please give me a time

**Comment by andrejunges** [comment]
@bokuweb I can do an PR with this fix.

Just to confirm, should I go for passing the whole event on `onTouchStart` and checking it on `onResizeStart` https://github.com/bokuweb/react-resizable-box/blob/master/src/index.js#L217

we could do something like
`const event = e.touches ? e.touches[0] : e`

**Comment by bokuweb** [comment]
@andrejunges thx!!

I think i should change bellow.

- https://github.com/bokuweb/react-resizable-box/blob/master/src/resizer.js#L91

``` javascript
  onTouchStart(event) {
    this.props.onResizeStart(event);
  }
```
