### ISSUE TITLE
scale causes position issue (controlled)

### ISSUE THREAD

**Issue by pixelass** [bokuweb/react-rnd#581]
### Overview of the problem

I'm using react-rnd **version** [10.0.0]   
      
My **browser** is:  Chrome 
   
I am sure this issue is **not a duplicate**? 

YES.
   
### Reproduced project

https://codesandbox.io/s/wonderful-sara-ntpno

### Description

When changing the scale the position of the Rnd elements is incorrect. (a simple zoom-in, then zoom-out demonstrates this very nicely)

### Steps to Reproduce

1. Use `size` and `position` properties
2. set scale (make it changeable)
3. When scale up changes to scale down the issue is visible.

### Expected behavior

Scale should not affect the position. The position should always remain relative to its wrapper

### Actual behavior

The element jumps (jumps increase with increasing x | y positions)

![rnd_issue](https://user-images.githubusercontent.com/1148334/63656055-dcca3180-c78f-11e9-9e4d-307d18b6a8fc.gif)
![rnd_issue_2](https://user-images.githubusercontent.com/1148334/63656060-e0f64f00-c78f-11e9-8b94-177d93d783aa.gif)

**Comment by zhangwei900808** [comment]
same problem

**Comment by pixelass** [comment]
@zhangwei900808  
I am currently working on a new library that attempts to tackle a lot of open issues from this project.

Project:  
https://github.com/dekk-app/react-mops/tree/master/packages/react-mops

Current testing sandbox:  
https://codesandbox.io/s/react-mops-4cwhx

![mops_scale](https://user-images.githubusercontent.com/1148334/65408973-e7a3d080-dde6-11e9-9278-49d12fa9b667.gif)

**Comment by OskarAhl** [comment]
Solved this by adding `position: relative` to the parent element (i.e. to the "bounds" parent element)

**Comment by Slapbox** [comment]
@OskarAhl that doesn't do it for me.

**Comment by flwzz** [comment]
> Solved this by adding `position: relative` to the parent element (i.e. to the "bounds" parent element)

that doesn't work.

**Comment by Dror-Bar** [comment]
Solved with the built-in prop: `scale`

example: https://codesandbox.io/s/vmo9ypvwl7

**Comment by rxliuli** [comment]
> Solved with the built-in prop: `scale`
> 
> example: https://codesandbox.io/s/vmo9ypvwl7

But when it is used with another configuration item `bounds`, it will cause an error

refer to: <https://codesandbox.io/s/naughty-moore-4tbdl?file=/src/index.js:487-493>
