### ISSUE TITLE
maintenance status?

### ISSUE THREAD

**Issue by pixelass** [bokuweb/react-rnd#590]
I was wondering if this repository is still actively maintained. 

Since it seems pretty stale (considering new features) I went ahead and wrote a small library to handle several features one would expect from a library like this.

In general I'd be open to contributing before I publish yet another package on npm. 

My implementation handles the following cases: (currently only for OS X)

* rotation (through CMD)
  * SHIFT rotates in step of 15deg
  * respects scale
* resize
  * SHIFT maintains aspect-ratio
  * ALT resizes left|right and/or top|bottom synchronously
  * respects scale
* drag
  * allows custom snap logic (including custom boundaries or collision) 
  * respects scale

![drr](https://user-images.githubusercontent.com/1148334/64690789-83514a80-d491-11e9-8be2-b8305817693c.gif)

**Comment by volkandkaya** [comment]
Looks great. Hopefully can be added here.

**Comment by pixelass** [comment]
It would be a complete rewrite though. 
It is a standalone component (no underlying resize & drag libraries)
I am using react-hooks and styled-components and currently looking into removing styled-components.

I'll push it to a remote git repo once done. I guess this will help you decide how well it fits here.

**Comment by pixelass** [comment]
In case anybody is interested in my library:

Source: https://github.com/dekk-app/react-mops  
Demo: https://react-mops.netlify.com/

![mops_combined](https://user-images.githubusercontent.com/1148334/65252974-25a8a800-dafa-11e9-9917-3ac90e256264.gif)


*It hasn't been released yet since I want to get rid of the dependency to styled-components first and rethink the snapping logic*
