### ISSUE TITLE
Chrome: rnd combine with animation: can't render correctly view when dragging

### ISSUE THREAD

**Issue by nhungnguyen3011** [bokuweb/react-rnd#606]
This is a bug and just happen on Chrome (78.0.3904.97 - lastest version for now)

### Overview of the problem

I'm using react-rnd **9.1.2**, but this bug also occurs when using 10.1.1.
   
I am sure this issue is not a duplicate. Tried to find a similar issue but there's nothing relevant.
   
### Reproduced project
Using <Rnd/> with children is an animated component, the drag/drop behavior isn't work properly anymore.
See more at
https://codesandbox.io/embed/hungry-glitter-n0kps?fontsize=14

### Workaround: 
Currently we just disable all animation when dragging

**Comment by joealden** [comment]
This is also happening for our team in Chrome `78.0.3904.97`, but I have noticed this before in previous chrome versions, so I'm not sure it is specific to this exact version.

In my case, when displaying a spinner animated using CSS (shown in the below screenshot, it just rotates infinitely), if the user moves the draggable container, only some of the contents of the draggable seems to repaint correctly. Sometimes, the browser manages to repaint in the correct location, but this only seems to happen if you drag the draggable container far enough from where it was positioned when it painted correctly.

It's also worth noting that as shown in the below screenshot, when inspecting elements in the draggable container using the browser element inspector, the browser element highlighter correctly shows where the element should be, not where it is has actually been painted:

![screenshot](https://user-images.githubusercontent.com/10297243/69584937-4992d900-0fd6-11ea-83a1-247b7910b9f7.png)

In the above screenshot, `1` shows where the selected element has actually been painted, `2` shows where the browser says the element is on the page, and `3` shows that the highlighted element (`2`) is indeed the same element as `1` (you can see by the text content of "Refreshing Accounts").

As the browser shows the highlight of the inspected element differently to where it is actually painted on the page, is this possibly a browser paint bug with Chrome? I don't see why this scenario should ever should ever happen in user land code, so I am guessing that the combination of the draggable container and the animation inside it is somehow causing Chrome to think it doesn't need to repaint.

---

@bokuweb I apologise for tagging you in this issue directly, but I was wondering what you thought about this. Is the only reasonable explanation for this that it is a browser bug?

**Comment by bokuweb** [comment]
@joealden Thanks :+1: But I can not have  enough time to do investigation now.. Please wait...

**Comment by ignapas** [comment]
To disable animations while dragging:
* Add a class to the animated item:
```jsx
<CircularProgress className='animated' />
```
* In your css:
```css
.react-draggable-dragging .animated {
  animation: none;
}
```

**Comment by nhungnguyen3011** [comment]
Currently, this issue doesn't happen anymore with the Chromium browsers (Chrome version > 80, Edge Chromium)
Seem like this bug is because of Chromium :))

I closed this ticket.

Thanks for your interest!
