### ISSUE TITLE
can't use rotate in Rnd

### ISSUE THREAD

**Issue by kele5240** [bokuweb/react-rnd#608]
i want use rotate in Rnd, but it will be rewrite by translate.
when i use transform other parameter, only translate left.

for example, i want transform: translate(100px, 100px) rotate(15deg);  in Rnd is  transform: translate(100px, 100px); rotate has been lost

**Comment by adanielyan** [comment]
I am having the same issue. I couldn't find where in the source code the transform is applied.

**Comment by adanielyan** [comment]
OK, it turns out the translate transform is set in react-draggable.

**Comment by bokuweb** [comment]
duplicated #230
