### ISSUE TITLE
pointerEvents being triggered when dragging over iframe

### ISSUE THREAD

**Issue by pixeliner** [bokuweb/react-rnd#609]
Well it seems none of the draggable react components out there actually take PointerEvents into account. Same as for this component.

So when you include iframes in your view, whether it be in the Rnd component or outside, the moment you drag/resize over an iframe and your mouse pointer is close to the edge, all interactions are lost and you focus the iframe again.

example (drag light gray area over the blue iframe):
https://codesandbox.io/s/hungry-wing-erk39?fontsize=14&hidenavigation=1&theme=dark

**Comment by pixeliner** [comment]
Well I eventually fixed it like so:

```
const toggleIframePointerEvents = useCallback((disable = false) => {
    [...document.getElementsByTagName('iframe')].forEach((iframe) => {
      // eslint-disable-next-line no-param-reassign
      iframe.style.pointerEvents = disable ? 'none' : 'auto';
    });
  }, []);

  const onDragStartHandler = useCallback(() => {
    toggleIframePointerEvents(true);
  }, [toggleIframePointerEvents]);

  const onDragStopHandler = useCallback((e, d) => {
    setPosition({ x: d.x, y: d.y });
    toggleIframePointerEvents(false);
  }, [toggleIframePointerEvents]);

  const onResizeStartHandler = useCallback((e, direction, ref, delta, pos) => {
    toggleIframePointerEvents(true);
    setSize({ height: ref.offsetHeight, width: ref.offsetWidth });
    setPosition(pos);
  }, [toggleIframePointerEvents]);

  const onResizeStopHandler = useCallback((e, direction, ref, delta, pos) => {
    setSize({ height: ref.offsetHeight, width: ref.offsetWidth });
    setPosition(pos);
    toggleIframePointerEvents(false);
  }, [toggleIframePointerEvents]);
```

Not a super "clean" solution, but simple. If anyone has some other idea, do share :)

**Comment by dguayrobotiq** [comment]
Any clean fix for this? Above code works but I'd rather not have to handle this on my end.

**Comment by tatsmaki** [comment]
> Any clean fix for this? Above code works but I'd rather not have to handle this on my end.

I fixed it with setting zIndex of iframes to -1 when onDragStart happens and back to normal onDragStop
same with onResize events

**Comment by gwhizoftv** [comment]
IMHO this issue is not closed. When I have an iframe inside Rnd, my cursor never turns to drag cursor and I cannot drag the element at all.
