### ISSUE TITLE
Resizer div sizes

### ISSUE THREAD

**Issue by cherya** [bokuweb/react-rnd#61]
Is it possible to change resizer div size and position? By default they are "height:10px" or "width: 10px".
How can I make them "height:4px" or "width: 4px" and move them a little inside?

**Comment by bokuweb** [comment]
@cherya Please, use [`ResizerHandleStyle`](https://github.com/bokuweb/react-rnd#resizerhandlestyle-proptypesshape-top-proptypesobject-right-proptypesobject-bottom-proptypesobject-left-proptypesobject-topright-proptypesobject-bottomright-proptypesobject-bottomleft-proptypesobject-topleft-proptypesobject-) to set style to handler.

**Comment by cherya** [comment]
@bokuweb thank you!
