### ISSUE TITLE
position Is wrong when onResize

### ISSUE THREAD

**Issue by kele5240** [bokuweb/react-rnd#618]
![1](https://user-images.githubusercontent.com/344451/70587906-343cc200-1c06-11ea-81c7-b12869fe0f17.gif)

move box  ->  resize it  ->  move it  -> click one corner of this box

just like the gif.

**Comment by bokuweb** [comment]
fxied by #619

**Comment by bokuweb** [comment]
@kele5240 Thanks for your report!! This issue is fixed by v10.1.3. Please try latest version.
