### ISSUE TITLE
onResize callback

### ISSUE THREAD

**Issue by harivasista** [bokuweb/react-rnd#64]
Hello Bokuweb,

I have a shape (eg. square or rectangle) inside Rnd component and if I resize the component I would want the shape also to resize accordingly. How will I be able to achieve this onResize ?

Thanks.

**Comment by bokuweb** [comment]
@harivasista 

Please recieve delta `width` and `height` from `onResize` callback,  then re-calculate your shape size from these value, and set new style to your shape.

**Comment by harivasista** [comment]
Thanks a lot for the response. But it worked for me when I set the states using the ClientSize. Could you please explain more about the styleSize and clientSize differences ?
