### ISSUE TITLE
I need help: why 'dragAxis' didn't work?

### ISSUE THREAD

**Issue by changzhn** [bokuweb/react-rnd#650]
I just want the element move on the x-axis; And I set the `{dragAxis: 'x'}`, but element can move on the y-axis;
All configuration information is as follows：
```
<Rnd
        style={{cursor: 'pointer'}}
        bounds="parent"
        enableResizing={{
          bottom: false,
          bottomLeft: false,
          bottomRight: false,
          left: false,
          right: false,
          top: false,
          topLeft: false,
          topRight: false,
        }}
        dragAxis="x"
        position={{ x: leftPx, y: 4 }}
        onDrag={(e, d) => onTimeUpdate((d.x / width) * duration)}
      >
        <div>abc</div>
      </Rnd>
```

### Overview of the problem

I'm using react-rnd **version** [x.x.x]   
      "react-rnd": "10.1.3"
My **browser** is:   
   "chrome": "80.0.3987.116"
I am sure this issue is **not a duplicate**?
   
### Reproduced project

https://codesandbox.io/s/y3997qply9

### Steps to Reproduce

1. First Step
2. Second Step
3. and so on...

**Comment by bokuweb** [comment]
@changzhn Could you please provide a reproduced sample in codesandbox?
