### ISSUE TITLE
Question: How can controll elements not overlaps?

### ISSUE THREAD

**Issue by vankid88** [bokuweb/react-rnd#654]
### Overview of the problem

I'm using react-rnd **version** [x.x.x]   
      
My **browser** is:   
   
I am sure this issue is **not a duplicate**?
   
### Reproduced project

https://codesandbox.io/s/y3997qply9

### Steps to Reproduce

1. First Step
2. Second Step
3. and so on...

**Comment by kaipradel** [comment]
Use the bounds property which specifies movement boundaries.

**Comment by bokuweb** [comment]
Please control x and y by yourself.
