### ISSUE TITLE
updateOffsetParent method return left and top is error

### ISSUE THREAD

**Issue by FEliuyg** [bokuweb/react-rnd#655]
### Overview of the problem

I'm using react-rnd **version** [10.1.6]   
      
My **browser** is:   chrome
   
I am sure this issue is **not a duplicate**?
   
### Reproduced project

https://codesandbox.io/s/keen-bas-zqtoh

### Steps to Reproduce

- 1.add parent's parent's style with transform:scale(0.5)
- 2.the rnd component show error position

### Expected behavior

show exact position

**Comment by bokuweb** [comment]
@FEliuyg Please use `scale={0.5}`

**Comment by FEliuyg** [comment]
@bokuweb thanks for your answer.but i still have some problems
- if serveral parent node set transform:scale, it should calculate the result scale, how to use it easy?
- if parent node transform: scale(0.5, 0.8), how to set the scale props?

**Comment by wmy94827** [comment]
> @bokuweb谢谢你的回答， 但我还是有些问题
> 
> * 如果服务器父节点设置转换：比例，它应该计算结果尺度，如何轻松使用？
> * 如果父节点转换：比例（0.5，0.8），如何设置比例道具？我更新[演示](https://codesandbox.io/s/keen-bas-zqtoh)

我也想知道这个问题怎么处理的~
