### ISSUE TITLE
Drag only when click header

### ISSUE THREAD

**Issue by rullymartanto** [bokuweb/react-rnd#659]
Hi, it's possible if we only drag the element using it's header ?

Thanks

**Comment by jensaxena** [comment]
Hi @rullymartanto - you can set dragHandleClassName to your header class, something like this:

```
<Rnd dragHandleClassName="window-header">
    <header className="window-header"></header>
</Rnd>
```

**Comment by rullymartanto** [comment]
thanks for help !
