### ISSUE TITLE
Is there a way to move the element using props ?

### ISSUE THREAD

**Issue by ioRekz** [bokuweb/react-rnd#66]
Right now, I have to use React lifecycle method to update the position when props change.

This could be easier if changing the initial props rerender the component  with new settings

**Comment by bokuweb** [comment]
@ioRekz Sorry, please use update position method.  https://github.com/bokuweb/react-rnd#updateposition-x-number-x-number-

**Comment by harivasista** [comment]
Hi even I am trying to update the position of the element. Could someone give me an example of doing it. As I have tried to call the update() function in a callback method and was unable to move the element. Could someone help me on this ?

**Comment by sajadghawami** [comment]
`this.rnd.updatePosition({x: newX, y: newY});`
