### ISSUE TITLE
[Improvement] Update dependencies

### ISSUE THREAD

**Issue by altro3** [bokuweb/react-rnd#699]
Hi! Thank you for this good wrapper for draggable library. I try to find good library to create movable and resizeble window inside my web-app  so much time. And only your library now meets all my requirements. That is, only here I found simple mechanisms for setting up the element as I need. Thanks!

Maybe need to update dependecnies to current versions?

react-draggable 4.2.0 -----> **4.4.2**
re-resizable 6.3.2 ----> **6.4.0**
tslib  1.11.1 -----> **2.0.0**

**Comment by bokuweb** [comment]
@altro3 Thanks I'll try it

**Comment by altro3** [comment]
@bokuweb Thank! But it’s not as important as that - https://github.com/bokuweb/react-rnd/issues/698

I am not a professional in Javascript, I specialize in backend development. And I think that it will take me a lot of time to fix it myself

Please look at this bug - I spent more than two hours to understand why I sometimes lose the draggable element
