### ISSUE TITLE
touch devices - onDragStop positions is NaN

### ISSUE THREAD

**Issue by Hazantip** [bokuweb/react-rnd#72]
`onDragStop` has a callback `{ event, ui: { position ... } }`, and on touch devices here is top and left positions equals NaN, on if event is mouse, all ok.

**Comment by bokuweb** [comment]
@Hazantip thanks for your report, I'll investigate it.

**Comment by Hazantip** [comment]
@bokuweb onDrag return correct data, maybe you can take a look on how you implemented onDrag and this might help you to solve problem with onDragStop

**Comment by bokuweb** [comment]
react-rnd@5.0.0 published. The latest react-draggable is used in @5.0.0. Is this resolved?

**Comment by bokuweb** [comment]
Could you please reopen  if you need.
