### ISSUE TITLE
Controlled draggable position is messed up by transform

### ISSUE THREAD

**Issue by nicholaschiang** [bokuweb/react-rnd#720]
### Overview of the problem

I'm using react-rnd **version** ^10.2.1
      
My **browser** is:   Firefox
   
I am sure this issue is **not a duplicate**? Yup, I'm pretty sure. It might be a duplicate, but all the similar-sounding issues were very vague, so I can't be sure.

### Description

The `transform` property set by `react-draggable` conflicts with our position property **until** the user clicks on the `Rnd`:

![react-rnd](https://user-images.githubusercontent.com/20798889/88860004-bdadfe00-d1af-11ea-975c-755ef44a0fed.gif)

Once the user clicks on the `Rnd`, it seems to reset the `transform` property and the component is correctly positioned again (even though the `position` and `size` never actually changed):

### Expected behavior

The user shouldn't have to click on it for the `react-draggable` to re-position correctly. The `transform` property should be set to 0 initially and set the `top` and `left` values based on the given `position`.

### Actual behavior

See the GIF above.

**Comment by nicholaschiang** [comment]
Fixed this myself. The problem was that the parent's `display` was changing **after** `react-draggable` was initialized.

**Comment by nicefella** [comment]
Very same problem. But in my case, it doesn't seem that the parent's `display` is changing, it is always 'flex'
