### ISSUE TITLE
[Bug] Button press not working on touch devices

### ISSUE THREAD

**Issue by kabeer10395** [bokuweb/react-rnd#760]
It is a bug

browser bug

### Overview of the problem

The Button press on touch devices is not woking but works with mouse click

I'm using react-rnd **version** [10.2.4]   

My **browser** is:   Chrome

### Reproduced project
https://codesandbox.io/embed/epic-wave-7f82y

Open in mobile browser or toogle device ToolBar

**Comment by bokuweb** [comment]
@kabeer10395 Thanks:)

Please use `cancel` like following.

``` TypeScript
  <Rnd
    style={style}
    default={{
      x: 0,
      y: 0,
      width: 320,
      height: 200,
    }}
    cancel="cancel"
  >
    <button className="cancel" onClick={() => alert("clciked")}>Clkck me</button>
  </Rnd>
```

ref: https://github.com/STRML/react-draggable/pull/470

**Comment by kabeer10395** [comment]
downgrade to version **10.1.10** works :) thx

**Comment by simlmx** [comment]
Same problem. The only thing that worked was downgrading to `10.1.10`!

**Comment by valerii15298** [comment]
@bokuweb unfortunately this solution reduces flexibility very much. On my moible device I wanna open dialog on double click on whole Rnd item. But when I use `cancel` the drag/resize behaviour does not work.
Are there any workarounds to implement double click to the whole Rnd item?

This does not work:
```tsx
<Rnd
cancel="#hello"
>
<button onDoubleClick={() => console.log("I hope this could be logged on double click")} id="hello">Hello</button>
</Rnd>
```
