### ISSUE TITLE
the problem of draging picture

### ISSUE THREAD

**Issue by mfma** [bokuweb/react-rnd#79]
Drag the picture, the original picture did not follow the move, is a relatively low transparency of the picture with the mouse moving. At the end of the drag and release the mouse, the original image will be moved to the location of the end of the drag and drop, and if this time to move the mouse, the original image can be moved
![qq 20170301145150](https://cloud.githubusercontent.com/assets/5546094/23448906/a6e76f3c-fe8e-11e6-85bd-44fd35f86df8.png)

**Comment by mfma** [comment]
Because the img tag is default support the draggable attribute ，and therefore setting the draggable attribute to false can solve the problem

**Comment by bokuweb** [comment]
Please set `draggable=false` or use `event.preventDefault()`.

**Comment by dholakiyaankit** [comment]
event.preventDefault(); works like a charm, I was having issue when I start dragging the image attached to my mouse and it keeps moving with my mouse. I resolved it using preventdefault.

**Comment by Dror-Bar** [comment]
@bokuweb Thanks, draggable=false on the img component was enough for me.
This is easy to miss and a common thing to happen, I think it should be more clear in the Read Me.
