### ISSUE TITLE
BUG: Top and left resize issue, Caused by "position"

### ISSUE THREAD

**Issue by shunyue1320** [bokuweb/react-rnd#792]
### Overview of the problem

I'm using react-rnd **version** [10.3.0]   
      
My **browser** is:   Chrome Version 90.0.4430.212
   
I am sure this issue is **not a duplicate**?
   
### Reproduced project

https://codesandbox.io/s/bug-wd7ql

### Steps to Reproduce

1.  react-rnd **version** [10.3.0]   
2.  Rnd component add "position" parameter
3.  top and left resize cause problems
```jsx
<Rnd
  style={style}
  size={{ width: this.state.width, height: this.state.height }}
  position={{ x: this.state.x, y: this.state.y }}     {/* add "position" top and left resize cause problems  */}
  onDragStop={(e, d) => {
    this.setState({ x: d.x, y: d.y });
  }}
  onResizeStop={(e, direction, ref, delta, position) => {
    this.setState({
      width: ref.style.width,
      height: ref.style.height,
      ...position
    });
  }}
>
  top and left resize issue
</Rnd>
```

### Expected behavior

bug: The bottom changes when you drag the top, and the left changes when you drag the right

### Actual behavior

The top changes when you drag the top, and the right changes when you drag the right

**Comment by bokuweb** [comment]
@shunyue1320 Thnaks. v10.3.1 published, please try it.

**Comment by shunyue1320** [comment]
@bokuweb  thank you.
