### ISSUE TITLE
onDrag callback not called when dragAxis = "none"

### ISSUE THREAD

**Issue by chainworksdigital** [bokuweb/react-rnd#821]
Question/Feature

### Overview of the problem
`onDrag` behavior in react-rnd when `dragAxis="none"` is different from `onDrag` behavior in react-draggable when `axis="none"`. Because of this, I'm not able to fully control the position of the dragged element. 

I'm using react-rnd **version** 10.3.4   
      
My **browser** is:   Chrome 92.0.4515.131 (Official Build) (64-bit)
   
I am sure this issue is **not a duplicate**?
No
   
### Reproduced project

https://codesandbox.io/s/zealous-merkle-y5e1w?file=/src/index.js

### Description

I have a use-case where I require full control over the position of the dragging element **while dragging**. Using react-draggable, I can do that by specifying `axis="none"` and manually updating the position of the element and using the data received in the `onDrag` callback. But when I try to do the same with react-rnd by setting `dragAxis="none"`, no events are being fired in the `onDrag` callback. If I try to set `dragAxis="both"` and control the position based on the callback values, the position is being updated only  after the drag is stopped, not while the element is being dragged.

Looking at react-draggable's README, it clearly mentions that `onDrag` gets called even in cases where `axis` is set to `none`
```
// Determines which axis the draggable can move. This only affects
// flushing to the DOM. Callbacks will still include all values.
// Accepted values:
// - `both` allows movement horizontally and vertically (default).
// - `x` limits movement to horizontal axis.
// - `y` limits movement to vertical axis.
// - 'none' stops all movement.
axis: string,
```
Whereas in react-rnd the events are being swallowed [here](https://github.com/bokuweb/react-rnd/blob/5c36fffac3b804e1b77793f9d3466577fb34aef1/src/index.tsx#L363) and [here](https://github.com/bokuweb/react-rnd/blob/5c36fffac3b804e1b77793f9d3466577fb34aef1/src/index.tsx#L375)

Is this behavior expected ?

**Comment by bokuweb** [comment]
> Is this behavior expected ?

Yes, it is expexted behavior on rnd

**Comment by chainworksdigital** [comment]
@bokuweb In that case, is there a way in current rnd to control the element while dragging, or are there any plans to enable that feature ? If not, looks like the only way forward for me is to fork and customize the module.

**Comment by pahen** [comment]
Seems like this commit changed the behaviour: https://github.com/bokuweb/react-rnd/commit/4f6ebde73cd6135457e424daf419b62f0ed457e1
