### ISSUE TITLE
Resize and Draggable icons for user to know that window is RnD

### ISSUE THREAD

**Issue by fatinWasta** [bokuweb/react-rnd#824]
Is there any way that I can add the icon or something in UI where users can know that views are resizable and draggable?

Also, on the desktop, it already shows the arrows as soon as the user hovers to the bounds of view,  but it's difficult to user know if the user opens a webpage on mobile, cause there the user can not know that view is resizable and draggable. 

Asking for help on this one. 

Thanks.

**Comment by sujoyduttajad** [comment]
For Desktop mode -
You can use the styles property or create a class and change the `cursor: pointer !important` to override the element styles. 
Also to show correct resize pointers to give users that the item or the draggable component is resizable. For example, the below code will make the draggable component resize to the right and bottom sides.
`resizeHandleStyles={{
  right: {
      cursor: 'e-resize'
}, 
 bottom: {
      cursor: 's-resize'
}
}}`

For Mobile mode -
I think the users will get familiar with dragged and resized components once they start using the app. You can also use tooltips to guide the user about the various features of the app.

**Comment by fatinWasta** [comment]
Thanks. this helped @sujoyduttajad .
