### ISSUE TITLE
onResizeStop get the current element index or target

### ISSUE THREAD

**Issue by jcamposv14** [bokuweb/react-rnd#84]
Can I get the current element index or target when I onResizeStop and Drag ?

**Comment by bokuweb** [comment]
Please bind index for onResizeStop.

```
render() { 
  return <Rnd onResizeStop={onStop.bind(this, index)} />
}

onStop(index) {
  console.log(index);
}
```

I'm going to add target element to all callbacks for next verion (v5).please wait.

**Comment by jcamposv14** [comment]
thank you
