### ISSUE TITLE
Is there any way to allow to resize the element only by resizeHandleComponent?

### ISSUE THREAD

**Issue by soft2dev** [bokuweb/react-rnd#840]
question
No

### Overview of the problem

I'm using react-rnd **version** [x.x.x]   10.3.5
      
My **browser** is:   Chrome
   
I am sure this issue is **not a duplicate**? yes
   
### Reproduced project
 
https://codesandbox.io/s/optimistic-engelbart-n5ufy

### Description

I added handle resizeHandleComponent and now resizeHandleComponent is working but other resize option is also working.
Is there any way to disable resize element except resizeHandleComponent?

### Steps to Reproduce

1. First Step
2. Second Step
3. and so on...

### Expected behavior

Only resizeHandleComponent should work for resize.

### Actual behavior

Both resizeHandleComponent and other resize are working.

**Comment by homanp** [comment]
@soft2dev how did you achieve resizing only by handle?
