### ISSUE TITLE
Multiple Rnd 

### ISSUE THREAD

**Issue by jcamposv14** [bokuweb/react-rnd#85]
Hello I have Multiple Rnd element into a components and I need to get the current instance and call the function updatePosition but seems like all the Rnd is update it and I just need one. 

This is an example that I have , I removed others props
captions.captions.map(
          (caption, i) => <Rnd key={caption.id} ref={c => { this.rnd = c;}}
            initial={{
              x      : caption.position,
              y      : CAPTION_Y_POSITION,
              width  : caption.width,
              height : CAPTION_HEIGHT,
            }}
            bounds={'parent'}
            className={classes.box}
            minWidth={50}
            minHeight={50}
            maxWidth={2500}
            maxHeight={50}
            onDragStop={(event, ui)=>{
              updateCaptionRank(i, ui.position.left, caption.width);
              /* if (captions.resetPosition) {
                // Here is the issue sometimes get other box and not the current dragging box
                this.rnd.updatePosition({ x : caption.position, y : 0 });
              }*/
            }}
            onResizeStop={(dir, styleSize, clientSize, delta, newPos)=>{
              updateCaptionRank(i, newPos.x, clientSize.width);
            }}>
            <div className="box">
              {caption.copy}
            </div>
            <span className={classes.reactLeft}/>
            <span className={classes.reactRight}/>
            <span className={classes.edit} onClick={()=>captionUpdateMode(i)}/>
           </Rnd>
        )

**Comment by jcamposv14** [comment]
I think I fixed I added this.rnd = []; and into the map ref={c => { this.rnd[i] = c;} so when i call an method I use the index instance.

**Comment by bokuweb** [comment]
@jcamposv14 Looks good!
