### ISSUE TITLE
Publish v10.3.6?

### ISSUE THREAD

**Issue by TaylorBriggs** [bokuweb/react-rnd#860]
In the [Changelog](https://github.com/bokuweb/react-rnd#v1036) the latest version is shown as 10.3.6, but it is not published on npm. It seems like the version bump will fix a `setState` error in the Draggable component. 

<img width="1919" alt="Screen Shot 2022-04-11 at 6 02 09 PM" src="https://user-images.githubusercontent.com/1335519/162847053-e03d2888-06a9-4eb2-ad66-f4c6f676c823.png">

**Comment by bokuweb** [comment]
@TaylorBriggs Sorry, I published now
