### ISSUE TITLE
Support  span editablesu

### ISSUE THREAD

**Issue by mfma** [bokuweb/react-rnd#90]
When  press the Enter key, the span tag whitch the contenteditable attribute  is true cannot be displayed correctly

![11](https://cloud.githubusercontent.com/assets/5546094/25031599/8c766448-2100-11e7-803d-37001b4f2cb4.png)
![22](https://cloud.githubusercontent.com/assets/5546094/25031824/20e4301e-2102-11e7-8d4c-2843458c8892.png)

**Comment by bokuweb** [comment]
Would you please provide reproduced project in codesandbox?
