### ISSUE TITLE
Add option so that a window is only draggable by its top

### ISSUE THREAD

**Issue by deanm0000** [bokuweb/react-rnd#956]
This is a feature request
I'm using react-rnd **version** 10.4.13
My **browser** is:   Edge/Brave/Chrome

### Description

A lot of times I have text boxes, Chart.js graphs, or other children in my Rnd window where interacting with those children also drags the window or the dragging prevents doing things like highlighting text. Since windows (small "w") in desktop OS environments almost always only are draggable from their top bar, I thought that was a natural way to alleviate the dual interaction. 

### Reproduced project
[Here](https://codesandbox.io/p/sandbox/m6pftd) is how I implemented what I need. I'm sure there's a better approach than this but it works for me. It would be cool if there was something like this natively.

![rnd_example](https://github.com/user-attachments/assets/aed73039-0b1e-46d3-9123-d643d115d525)

**Comment by d-a-weston** [comment]
There is the `dragHandleClassName` property, which let's you set the drag handle by a class name. My solution for example:

```
    <Rnd
      dragHandleClassName="toolbar"
    >
      <div className="tool-bar" />
      <div>
        Content
      </div>
    </Rnd>

```

**Comment by deanm0000** [comment]
whoa, that's way cleaner, thanks for the tip.

**Comment by popring** [comment]
> What if I want some elements in the toolbar to not be draggable? Refer to the following demo. What should I do?🤔
> 
> https://codesandbox.io/p/sandbox/inspiring-browser-j3m7hw
> 
> <img alt="image" width="591" src="https://private-user-images.githubusercontent.com/31247906/395957218-7ab9a558-3f72-442e-ad26-c34996b233c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjM0MDQsIm5iZiI6MTczNDMyMzEwNCwicGF0aCI6Ii8zMTI0NzkwNi8zOTU5NTcyMTgtN2FiOWE1NTgtM2Y3Mi00NDJlLWFkMjYtYzM0OTk2YjIzM2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA0MjUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYmU5YjI1YjMxYmQxZTI0NTMzMDA4M2VmNmNhZmZkMWU0MDEwNTYxZGNkNjM2ZWU1YzFiMGIyOTc5YThhODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HfNWY5sktOFtNKm_ai-Q57wvybbNtddgwUVRhJy13ak">

Sorry, I found it, it turns out that you can use the `cancel` attribute 🫥

**Comment by d-a-weston** [comment]
You can probably close the issue at this point :)
