### ISSUE TITLE
Resize bounds not working for left and top directions

### ISSUE THREAD

**Issue by kudlajz** [bokuweb/react-rnd#97]
When I set bounds to `parent` and try to resize the box beyond the right or bottom border of the parent element, it works as expected, but when I try to resize the box beyond the top or left border of the parent element, it allows me to do that. I'll take a look at `react-resizable-box` and try to make a PR if I come with a solution.

**Comment by bokuweb** [comment]
@kudlajz Thanks for your report. sorry..., it is a bug.
i'll do investigation. it is maybe react-rnd bug.

**Comment by kudlajz** [comment]
@bokuweb Thank you, it'll be surely much faster for you to fix that.

**Comment by bokuweb** [comment]
@kudlajz Fixed by @5.0.3 🙏
